### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by andyblarblar** [ISC-Project-Phoenix/aeb_rs#1]
- [x] Make the grid type
- [x] Make the kinematics equation
- [x] Make the range type and interface
- [x] Create public API that you actually use to find a collision (just like a function that takes a slice of points and returns colliding with info if a collision occurs)
- [x] Add collision box 
- [x] Add rasterisation algo
